spring:
    application:
        name: hibernate

    jackson:
        property-naming-strategy: SNAKE_CASE

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${DATABASE_DDL_OPTION:none}
        show-sql: ${DATABASE_SQL_LOG:false}

springdoc:
    api-docs:
        enabled: ${API_DOCS_ENABLED:false}

    swagger-ui:
        enabled: ${API_DOCS_ENABLED:false}
        tags-sorter: alpha
        operations-sorter: method
